export { default as Main } from './Main'
export { default as Welcome } from './Welcome'
export { default as About } from './About'
export { default as Portfolio } from './Portfolio'
export { default as Navbar} from './Navbar'
export { default as Footer } from './Footer'
